build:
  maxIssues: 0

complexity:
  LongMethod:
    threshold: 60
    ignoreAnnotated:
      - Composable
  LongParameterList:
    functionThreshold: 8
    constructorThreshold: 10
    ignoreAnnotated:
      - Composable
  TooManyFunctions:
    thresholdInFiles: 20
    thresholdInClasses: 15

exceptions:
  TooGenericExceptionCaught:
    active: true
    exceptionNames:
      - ArrayIndexOutOfBoundsException
      - IndexOutOfBoundsException
      - IllegalStateException
      - NullPointerException
    allowedExceptionNameRegex: '_|(ignore|expected).*'

style:
  MagicNumber:
    active: false
  ForbiddenComment:
    active: false
  MaxLineLength:
    maxLineLength: 120
    excludeCommentStatements: true
  WildcardImport:
    active: true
    excludeImports:
      - kotlinx.coroutines.flow.*
potential-bugs:
  UnsafeCallOnNullableType:
    active: true

naming:
  FunctionNaming:
    functionPattern: '[a-zA-Z][a-zA-Z0-9]*'
  TopLevelPropertyNaming:
    constantPattern: '[A-Za-z][_A-Za-z0-9]*'

formatting:
  active: true
  android: true
  Indentation:
    active: true
    indentSize: 4
  MaximumLineLength:
    active: true
    maxLineLength: 120
  ImportOrdering:
    active: true
  NoBlankLineBeforeRbraceRule:
    active: true
  NoConsecutiveBlankLines:
    active: true
  NoEmptyClassBody:
    active: true
  NoLineBreakAfterElse:
    active: true
  NoLineBreakBeforeAssignment:
    active: true
  NoMultipleSpaces:
    active: true
  NoSemicolons:
    active: true
  NoTrailingSpaces:
    active: true
  NoUnusedImports:
    active: true
  NoWildcardImports:
    active: true
  SpacingAroundColon:
    active: true
  SpacingAroundComma:
    active: true
  SpacingAroundCurly:
    active: true
  SpacingAroundKeyword:
    active: true
  SpacingAroundOperators:
    active: true
  SpacingAroundParens:
    active: true
  SpacingAroundRangeOperator:
    active: true
  TrailingCommaOnCallSite:
    active: false
  TrailingCommaOnDeclarationSite:
    active: false
